NAME = "GlyphaIII"
SRCS = \
	App.cpp \
	../game/GLGame.cpp \
	../game/GLImage.cpp \
	../game/GLRect.cpp \
	../game/GLRenderer.cpp \
	../game/GLSounds.cpp \
	../game/GLUtils.cpp \
	../themes/glyphaiii/images/background.c \
	../themes/glyphaiii/images/numbers.c \
	../themes/glyphaiii/images/platforms.c \
	../themes/glyphaiii/images/player.c \
	../themes/glyphaiii/images/playerIdle.c \
	../themes/glyphaiii/images/torches.c
LIBS = be GL png

include /boot/develop/etc/makefile-engine
