NAME = "GlyphaIII"
SRCS = \
	main.cpp \
	../game/GLGame.cpp \
	../game/GLImage.cpp \
	../game/GLRect.cpp \
	../game/GLRenderer.cpp \
	../game/GLResources.cpp \
	../game/GLSounds.cpp \
	../game/GLUtils.cpp \
LIBS = be GL png

include /boot/develop/etc/makefile-engine
